### ISSUE TITLE
Creation of requirements.txt file

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#10]
It would be useful to create a requirements.txt file for installing all libraries. I usually do that with:

``` shell
pip install pipreqs
pipreqs /path/to/project
```

@mozzherina , if you have a better idea, please let me know.

**Comment by pedropaulofb** [comment]
@mozzherina, please solve this issue only **after** the re-generation of the dataset.

**Comment by mozzherina** [comment]
[requirements.txt](https://github.com/unibz-core/Scior-Tester/files/10429452/requirements.txt)
Created.
