### ISSUE TITLE
New information to be registered in times csv file

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#11]
To allow comparison between different times files, it is necessary to register if the tests that generated these files were performed under similar configurations. To do that, we need to create (a) a file to register the computer configuration, or (b) to include this data into the files that already exist.

I opted for option b. @mozzherina , if you prefer something else, please let me know.

Option b can be implemented by creating the four last columns [already described here](https://github.com/unibz-core/OntCatOWL-Dataset/blob/main/documentation/OntCatOWL-Dataset-Test1.md#execution-times-csv-files). Even their formulas are already presented.

**Comment by pedropaulofb** [comment]
We also need to include the Scior version used in the tests in the result file. I added the field scior_version to the [Execution Times csv file](https://github.com/unibz-core/OntCatOWL-Dataset/blob/main/documentation/OntCatOWL-Dataset-Test1.md#execution-times-csv-files). Please check it there. 

To allow you to have access to the OntCatOWL's `main.py` global variable `SOFTWARE_VERSION`, I added it as a return value in the `run_ontcatowl_tester` function in the software's most recent version (2022.01.09).

@mozzherina, if you prefer an option different than b, we need to change the documentation.

@mozzherina, please solve this issue **before** the re-generation of the dataset.

**Comment by pedropaulofb** [comment]
We created the settings _csv_ file, which is [described here](https://github.com/unibz-core/OntCatOWL-Dataset/blob/main/documentation/OntCatOWL-Dataset-Test1.md#settings-csv-files).

**Comment by mozzherina** [comment]
Settings file contains all the necessary information.
