### ISSUE TITLE
Change of data_XXX_txYYY.csv file columns' names

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#13]
For improving the readability, please substitute the name of the column in the data_XXX_txYYY.csv file in the generation code as follows:

**- Substitution 1:**
 - before: stereotype_original
 - after: ontouml_stereotype

**- Substitution 2:**
 - before: stereotype_gufo
 - after: gufo_classification

Also, make the adjustments in the related variables names if necessary.

I have already made the modifications in the documentation.

**Comment by pedropaulofb** [comment]
@mozzherina, please solve this issue **before** the re-generation of the dataset.

**Comment by mozzherina** [comment]
Done
