### ISSUE TITLE
Tester's arguments for executing Test 1 and Test 2

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#15]
The current implementation of the OntCatOWL-Tester's functions run_ontcatowl_test1 and run_ontcatowl_test2 receives the path to the *internal generated* catalog as a parameter, which is unnecessary. 

Please remove this argument for the test functions, keeping it for the build function (that uses the *external catalog* path).

In addition, please note that the item 4 reported at Issue #3 must be implemented for improving the software usability. I set it as necessary in the documentation.

**Comment by pedropaulofb** [comment]
@mozzherina, please solve this issue **before** the re-generation of the dataset.

**Comment by mozzherina** [comment]
Done:
parameters for build: -p external-path -b
parameters for run; -r1 -c -a
