### ISSUE TITLE
Project name changed to Scior

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#16]
The project's name was changed from **OntCatOWL** to **Scior**.

We need to substitute every occurrence of the term **OntCatOWL** to **Scior** in code, resources, and documentations.

In this case: Scior-Tester

**Comment by pedropaulofb** [comment]
@mozzherina, please solve this issue only after the re-generation of the dataset.

**Comment by mozzherina** [comment]
@pedropaulofb Partially done, waiting for Scior updates.

**Comment by pedropaulofb** [comment]
Done. @mozzherina, please proceed with this issue.

**Comment by mozzherina** [comment]
Done. Also updated the requirements with `git+https://github.com/unibz-core/Scior.git`
