### ISSUE TITLE
Creation of Knowledge Matrix files

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#18]
The most recent version of OntCatOWL publishes to the Tester a variable named `knowledge_matrix`.

I.e., I added the variable `knowledge_matrix` to the return statement of the `run_ontcatowl_tester` function in the OntCatOWL project's `main.py` file.

The knowledge matrix is nothing more than just a matrix of size 15x15 composed of integers that is generated after the execution of the software.

@mozzherina, please, implement the generation of a csv file according to the instructions for [Test 1](https://github.com/unibz-core/OntCatOWL-Dataset/blob/main/documentation/OntCatOWL-Dataset-Test1.md#knowledge-matrix-csv-files) and [Test 2](https://github.com/unibz-core/OntCatOWL-Dataset/blob/main/documentation/OntCatOWL-Dataset-Test2.md#knowledge-matrix-csv-files).

**Comment by mozzherina** [comment]
Created.
[matrix_aguiar2018rdbs-o_tt002_ac_tx001_ex010_pc020.csv](https://github.com/unibz-core/Scior-Tester/files/10429459/matrix_aguiar2018rdbs-o_tt002_ac_tx001_ex010_pc020.csv)
