### ISSUE TITLE
Creation of taxonomies.csv file

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#20]
Please add to the Tester's build function a new feature, the creation of the `taxonomies.csv` file ([specified here](https://github.com/unibz-core/OntCatOWL-Dataset#taxonomies-resume-csv-file)).

**Comment by pedropaulofb** [comment]
@mozzherina, please prioritize the generation of this file.

**Comment by mozzherina** [comment]
[The file was created](https://github.com/unibz-core/Scior-Dataset/blob/main/catalog/taxonomies.csv)
[taxonomies.csv](https://github.com/unibz-core/Scior-Tester/files/10429408/taxonomies.csv)
