### ISSUE TITLE
Inconsistencies Files without headers

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#21]
The "Inconsistencies _csv_ files" are being generated without headers. Please add it [as specified in here](https://github.com/unibz-core/OntCatOWL-Dataset/blob/main/documentation/OntCatOWL-Dataset-Test1.md#inconsistencies-csv-files).

**Comment by mozzherina** [comment]
Fixed. The issue was with file writing.
