### ISSUE TITLE
Improvements for the taxonomies.csv file

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#23]
Once we create the `taxonomies.csv` file (issue #20), we could improve it for a broader view of each taxonomy with the following information:

- number of root, leaf, and intermediate nodes
- number of each possible `ontouml_stereotype` (data before mapping) available in the taxonomies (i.e., a row for kind, role, etc., showing the number of these elements in the taxonomy)
- number of each possible gufo_classification (data after mapping) available in the taxonomies (i.e., a row for kind, role, etc., showing the number of these elements in the taxonomy)

After implementing this modification, we need to update the [Tester](https://github.com/unibz-core/OntCatOWL-Tester/blob/main/documentation/OntCatOWL-Tester-Build.md) and the [Dataset](https://github.com/unibz-core/Scior-Dataset#taxonomies-resume-csv-file) documentation.

**Comment by mozzherina** [comment]
Done. 
[taxonomies.csv](https://github.com/unibz-core/Scior-Tester/files/10450008/taxonomies.csv)
