### ISSUE TITLE
Creation of Settings file for Test 2

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#24]
@mozzherina, please create the Settings csv file for Test 2, as [specified here](https://github.com/unibz-core/Scior-Dataset/blob/main/documentation/Scior-Dataset-Test2.md#settings-csv-files).

This file is the same one that is already created for Test 1, but it is added with new columns representing Test 2's configurations.

**Comment by mozzherina** [comment]
Done. Updates in function save_platform_information
