### ISSUE TITLE
Update taxonomies.csv file

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#26]
I added two additional fields in the taxonomies.csv file so we can register important knowledge that was missing. The fields are: `num_mapped_classes` and `num_other_classes`. Please [check it here](https://github.com/unibz-core/Scior-Dataset/blob/main/README.md#taxonomies-resume-csv-file) and proceed with the implementation.

**Comment by mozzherina** [comment]
Done
[taxonomies.csv](https://github.com/unibz-core/Scior-Tester/files/10450202/taxonomies.csv)
