### ISSUE TITLE
Strategies for making the Tester more user-friendly

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#3]
Currently, for using the tester, a user must have to work directly on the code. Some features may make the Tester more user-friendly and could be considered.

1) We reported one of these strategies in Issue #2. Once the feature there reported is implemented, the user does not need to care about the source data location.

2) For Test 2, the user could give the following parameters as arguments or the tester could require the user to give this values after the test function is called (the parameters are hard-coded in the current version):
- MINIMUM_ALLOWED_NUMBER_CLASSES
- PERCENTAGE_INITIAL
- PERCENTAGE_FINAL
- PERCENTAGE_RATE
- NUMBER_OF_EXECUTIONS_PER_DATASET_PER_PERCENTAGE

**Comment by pedropaulofb** [comment]
3. Two different tests are implemented in the tester as of now: test1 and test2. The parameter -r calls all test functions, but we could separate it in -r1 and -r2 for calling the different tests.
4. the `is_automatic` and `is_complete` OntCatOWL argument is hard coded in the tester. We could keep the `is_automatic` as it is, but we should provide `is_complete` as an argument for running the tests (using -c or -n, as in OntCatOWL).

**Comment by mozzherina** [comment]
The constants are defined in .env file, the env.example is also provided. Libs that are used for this are typing (for Final) and python-decouple (for config).

**Comment by mozzherina** [comment]
> 3\. Two different tests are implemented in the tester as of now: test1 and test2. The parameter -r calls all test functions, but we could separate it in -r1 and -r2 for calling the different tests.

Implemented

**Comment by pedropaulofb** [comment]
Item 4 must be implemented. I set it as necessary in the documentation. Please check the Issue #15.

**Comment by pedropaulofb** [comment]
@mozzherina, please solve this issue only **after** the re-generation of the dataset.

**Comment by mozzherina** [comment]
Done. 
2 options:
AUTOMATIC=True
COMPLETE=True
are specified in .env, but the user can also run with -n/-c and -i/-a parameters for both tests.
