### ISSUE TITLE
Inclusion of sub_r_r rule at execution_times.csv file

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#6]
The current version of OntCatOWL (commit [81ad2f4](https://github.com/unibz-core/OntCatOWL/commit/81ad2f4f5e2bd1ddbf4e3f624f0daf0be89ab642)) provides the key `sub_r_r` at the `time_register` dictionary.  The value of this key is the total execution time of the rule "sub_r_r".

This `time_register` dictionary is used by the Tester for printing the _execution_times_N.csv_ files. Hence, please add another column in the header (alphabetically sorted) and also add the value of this key for each new line in the file.

**Comment by pedropaulofb** [comment]
@mozzherina, please solve this issue **before** the re-generation of the dataset.

**Comment by mozzherina** [comment]
@pedropaulofb, could you, please have a look at this file 
[times_aguiar2018rdbs-o_tt001_ac_tx001.csv](https://github.com/unibz-core/Scior-Tester/files/10438738/times_aguiar2018rdbs-o_tt001_ac_tx001.csv)
(as an example). Is it correct or not?

**Comment by mozzherina** [comment]
I've implemented alphabetic sort for keys.

**Comment by pedropaulofb** [comment]
Thank you. It seems to be correct.

**Comment by pedropaulofb** [comment]
@mozzherina, sorry, I closed the issue without the intention of doing it.

Please evaluate and close it yourself if you concluded it.

**Comment by mozzherina** [comment]
Done.
