### ISSUE TITLE
Change of inconsistencies_found.csv file column name

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#7]
For improving the readability, please substitute the name of the column in the `inconsistencies_found_N.csv` file as follows:

- before: `inconsistent_class_stereotype`
- after: `input_class_classification`

Also, make the adjustments in the related variables names if necessary.

**Comment by pedropaulofb** [comment]
For Test 2, please also perform the following modification:

- before: `percentage_test`
- after: `percentage`

**Comment by pedropaulofb** [comment]
@mozzherina, please solve this issue **before** the re-generation of the dataset.

**Comment by mozzherina** [comment]
@pedropaulofb Is it still actual? In the documentation it is [still the same](https://github.com/unibz-core/Scior-Dataset/blob/main/documentation/Scior-Dataset-Test1.md#inconsistencies-csv-files)

**Comment by pedropaulofb** [comment]
@mozzherina, yes, it is actual. Thanks for noticing and pointing me out that. I have already fixed that in the documentation.

**Comment by mozzherina** [comment]
Done
