### ISSUE TITLE
Change of results tests csv file columns names

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#8]
For improving the readability, please substitute the name of the column in the results_test_1_....csv file as follows:

- Column 1:
  - before: class_original_stereotype
  - after: class_original_classification
- Column 2:
  - before: stereotype_final_list
  - after: classification_final_list

Also, make the adjustments in the related variables names if necessary.

**Comment by pedropaulofb** [comment]
@mozzherina, please solve this issue **before** the re-generation of the dataset.

**Comment by mozzherina** [comment]
@pedropaulofb What is this results tests csv file? And where is it located?

**Comment by mozzherina** [comment]
Found. Fixed in simple_XXX...csv
