### ISSUE TITLE
Update of the name of all generated result files

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Tester#9]
Please adjust the name of the generated result files to correspond to the nomenclature [described here](https://github.com/unibz-core/OntCatOWL-Dataset#nomenclature-of-files-and-folders).

Examples of all files generated in Test 1 [can be found here](https://github.com/unibz-core/OntCatOWL-Dataset/blob/main/documentation/OntCatOWL-Dataset-Test1.md)
Examples of all files generated in Test 2 [can be found here](https://github.com/unibz-core/OntCatOWL-Dataset/blob/main/documentation/OntCatOWL-Dataset-Test2.md)

**Comment by pedropaulofb** [comment]
@mozzherina, please wait before starting to work on this issue because I am defining a nomenclature to be followed for all files and folders.

**Comment by pedropaulofb** [comment]
@mozzherina, please solve this issue **before** the re-generation of the dataset.

**Comment by mozzherina** [comment]
@pedropaulofb Everything is fine, except Divergences csv Files. What are they?

**Comment by pedropaulofb** [comment]
@mozzherina, thank you. 

Regarding the divergences csv files, they are generated for both [Test 1](https://github.com/unibz-core/Scior-Dataset/blob/main/documentation/Scior-Dataset-Test1.md#divergences-csv-files) and for [Test 2](https://github.com/unibz-core/Scior-Dataset/blob/main/documentation/Scior-Dataset-Test2.md#divergences-csv-files) (the links point to their documentations).

Please note that the inconsistencies and divergences files are only generated when at least one case is found during the test's execution.

**Comment by mozzherina** [comment]
Done. Divergencies files were created. 
[divergences_tt001_ac.csv](https://github.com/unibz-core/Scior-Tester/files/10450842/divergences_tt001_ac.csv)
